### ISSUE TITLE
grid_ggd doesn't need to vary in time for SOLPS data

### ISSUE THREAD

**Issue by eldond** [ProjectTorreyPines/SOLPS2IMAS.jl#2]
https://github.com/ProjectTorreyPines/SOLPS2IMAS.jl/blob/06d584e8e178a6e1ae00369a011efa0370564fe4/src/SOLPS2IMAS.jl#L348

If I understand this correctly, the current implementation allows for grid_ggd to vary in time. But for a SOLPS case, the grid will be fixed. So writing to grid_ggd should be outside of the loop over times, I think. I suspect this is part of why ggd and grid_ggd are separate in the first place.

**Comment by orso82** [comment]
yes, that's why at some point they moved grid_ggd outside of the arrays of structures

**Comment by anchal-physics** [comment]
Fixed in https://github.com/ProjectTorreyPines/SOLPS2IMAS.jl/commit/45cf74e0f50729e28c981b343bc032720177a6eb
In the latest dev branch, grid_ggd is outside the loop over time iterations of data.
