### ISSUE TITLE
Populate grid subsets for core, sol, and divertor cells

### ISSUE THREAD

**Issue by eldond** [ProjectTorreyPines/SOLPS2IMAS.jl#5]
It would be useful to be able to easily select cells that are in the core (within the separatrix, in the lobe that contains the magnetic axis (the private flux region could also be considered to be within the separatrix, but it doesn't count for this purpose)).
While doing this, might as well fill in the scrape-off layer (outside separatrix but above X-point; just use the mesh boundaries that pass through the X-point) and the divertor (below the X-point).

These are the subsets that contain groups of cells to define volumes (or areas if we're ignoring toroidal extent).

- [x] core: 22 (cells inside the active separatrix)
- [x] sol: 23 (cells defining the main SOL outside the divertor regions)
- [x] outer_divertor: 24 (cells defining the outer divertor region)
- [x] inner_divertor: 25 (cells defining the inner divertor region)

**Comment by anchal-physics** [comment]
Completed.
